-- Run while connected as VSLA_33365_2025_JOHN_DB in XEPDB1.
-- Core tables for the Community Savings Group (VSLA) system.

CREATE TABLE savings_groups (
    group_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    group_name        VARCHAR2(100) NOT NULL,
    location          VARCHAR2(100) NOT NULL,
    formation_date    DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    cycle_start_date  DATE NOT NULL,
    cycle_end_date    DATE NOT NULL,
    group_status      VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_savings_groups PRIMARY KEY (group_id),
    CONSTRAINT uq_savings_groups_name UNIQUE (group_name),
    CONSTRAINT chk_group_dates CHECK (cycle_end_date > cycle_start_date),
    CONSTRAINT chk_group_status CHECK (group_status IN ('ACTIVE', 'INACTIVE', 'CLOSED'))
);

CREATE TABLE members (
    member_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    group_id           NUMBER NOT NULL,
    member_number      VARCHAR2(20) NOT NULL,
    first_name         VARCHAR2(50) NOT NULL,
    last_name          VARCHAR2(50) NOT NULL,
    phone_number       VARCHAR2(20) NOT NULL,
    national_id        VARCHAR2(30),
    join_date          DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    membership_status  VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (member_id),
    CONSTRAINT fk_members_group FOREIGN KEY (group_id)
        REFERENCES savings_groups (group_id),
    CONSTRAINT uq_members_group_number UNIQUE (group_id, member_number),
    CONSTRAINT uq_members_national_id UNIQUE (national_id),
    CONSTRAINT chk_member_status CHECK (membership_status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE app_users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_id     NUMBER,
    username      VARCHAR2(50) NOT NULL,
    full_name     VARCHAR2(120) NOT NULL,
    user_role     VARCHAR2(20) NOT NULL,
    user_status   VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (user_id),
    CONSTRAINT fk_app_users_member FOREIGN KEY (member_id)
        REFERENCES members (member_id),
    CONSTRAINT uq_app_users_member UNIQUE (member_id),
    CONSTRAINT uq_app_users_username UNIQUE (username),
    CONSTRAINT chk_app_users_role CHECK (user_role IN ('ADMINISTRATOR', 'GROUP_LEADER', 'TREASURER', 'MEMBER')),
    CONSTRAINT chk_app_users_status CHECK (user_status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE meetings (
    meeting_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    group_id         NUMBER NOT NULL,
    meeting_date     DATE NOT NULL,
    venue            VARCHAR2(100) NOT NULL,
    meeting_status   VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    notes            VARCHAR2(500),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_meetings PRIMARY KEY (meeting_id),
    CONSTRAINT fk_meetings_group FOREIGN KEY (group_id)
        REFERENCES savings_groups (group_id),
    CONSTRAINT uq_meetings_group_date UNIQUE (group_id, meeting_date),
    CONSTRAINT chk_meetings_status CHECK (meeting_status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);

-- Verify the four core tables.
SELECT table_name
FROM user_tables
WHERE table_name IN ('SAVINGS_GROUPS', 'MEMBERS', 'APP_USERS', 'MEETINGS')
ORDER BY table_name;
