

CREATE TABLE contributions (
    contribution_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    meeting_id           NUMBER NOT NULL,
    member_id            NUMBER NOT NULL,
    contribution_amount  NUMBER(12,2) NOT NULL,
    payment_method       VARCHAR2(20) DEFAULT 'CASH' NOT NULL,
    received_by_user_id  NUMBER,
    contribution_date    DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    remarks              VARCHAR2(250),
    CONSTRAINT pk_contributions PRIMARY KEY (contribution_id),
    CONSTRAINT fk_contributions_meeting FOREIGN KEY (meeting_id)
        REFERENCES meetings (meeting_id),
    CONSTRAINT fk_contributions_member FOREIGN KEY (member_id)
        REFERENCES members (member_id),
    CONSTRAINT fk_contributions_user FOREIGN KEY (received_by_user_id)
        REFERENCES app_users (user_id),
    CONSTRAINT uq_contributions_member_meeting UNIQUE (meeting_id, member_id),
    CONSTRAINT chk_contributions_amount CHECK (contribution_amount > 0),
    CONSTRAINT chk_contributions_method CHECK (payment_method IN ('CASH', 'MOBILE_MONEY', 'BANK'))
);

CREATE TABLE loan_applications (
    application_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_id            NUMBER NOT NULL,
    application_date     DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    requested_amount     NUMBER(12,2) NOT NULL,
    loan_purpose         VARCHAR2(250) NOT NULL,
    application_status   VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    approved_amount      NUMBER(12,2),
    approved_by_user_id  NUMBER,
    approval_date        DATE,
    rejection_reason     VARCHAR2(250),
    CONSTRAINT pk_loan_applications PRIMARY KEY (application_id),
    CONSTRAINT fk_loan_apps_member FOREIGN KEY (member_id)
        REFERENCES members (member_id),
    CONSTRAINT fk_loan_apps_user FOREIGN KEY (approved_by_user_id)
        REFERENCES app_users (user_id),
    CONSTRAINT chk_loan_apps_requested CHECK (requested_amount > 0),
    CONSTRAINT chk_loan_apps_approved CHECK (approved_amount IS NULL OR approved_amount > 0),
    CONSTRAINT chk_loan_apps_status CHECK (application_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE loans (
    loan_id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    application_id      NUMBER NOT NULL,
    member_id           NUMBER NOT NULL,
    principal_amount    NUMBER(12,2) NOT NULL,
    interest_rate       NUMBER(5,2) DEFAULT 0 NOT NULL,
    disbursement_date   DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    due_date            DATE NOT NULL,
    loan_status         VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_loans PRIMARY KEY (loan_id),
    CONSTRAINT fk_loans_application FOREIGN KEY (application_id)
        REFERENCES loan_applications (application_id),
    CONSTRAINT fk_loans_member FOREIGN KEY (member_id)
        REFERENCES members (member_id),
    CONSTRAINT uq_loans_application UNIQUE (application_id),
    CONSTRAINT chk_loans_principal CHECK (principal_amount > 0),
    CONSTRAINT chk_loans_rate CHECK (interest_rate BETWEEN 0 AND 100),
    CONSTRAINT chk_loans_dates CHECK (due_date > disbursement_date),
    CONSTRAINT chk_loans_status CHECK (loan_status IN ('ACTIVE', 'PAID', 'OVERDUE', 'CANCELLED'))
);

CREATE TABLE loan_repayments (
    repayment_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    loan_id              NUMBER NOT NULL,
    repayment_date       DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    repayment_amount     NUMBER(12,2) NOT NULL,
    payment_method       VARCHAR2(20) DEFAULT 'CASH' NOT NULL,
    received_by_user_id  NUMBER,
    receipt_number       VARCHAR2(30) NOT NULL,
    remarks              VARCHAR2(250),
    CONSTRAINT pk_loan_repayments PRIMARY KEY (repayment_id),
    CONSTRAINT fk_repayments_loan FOREIGN KEY (loan_id)
        REFERENCES loans (loan_id),
    CONSTRAINT fk_repayments_user FOREIGN KEY (received_by_user_id)
        REFERENCES app_users (user_id),
    CONSTRAINT uq_repayments_receipt UNIQUE (receipt_number),
    CONSTRAINT chk_repayments_amount CHECK (repayment_amount > 0),
    CONSTRAINT chk_repayments_method CHECK (payment_method IN ('CASH', 'MOBILE_MONEY', 'BANK'))
);

CREATE TABLE penalties (
    penalty_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    loan_id            NUMBER NOT NULL,
    penalty_type       VARCHAR2(30) NOT NULL,
    penalty_amount     NUMBER(12,2) NOT NULL,
    penalty_date       DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    penalty_status     VARCHAR2(20) DEFAULT 'UNPAID' NOT NULL,
    remarks            VARCHAR2(250),
    CONSTRAINT pk_penalties PRIMARY KEY (penalty_id),
    CONSTRAINT fk_penalties_loan FOREIGN KEY (loan_id)
        REFERENCES loans (loan_id),
    CONSTRAINT chk_penalties_type CHECK (penalty_type IN ('LATE_REPAYMENT', 'MISSED_MEETING', 'OTHER')),
    CONSTRAINT chk_penalties_amount CHECK (penalty_amount > 0),
    CONSTRAINT chk_penalties_status CHECK (penalty_status IN ('UNPAID', 'PAID', 'WAIVED'))
);

CREATE TABLE share_outs (
    share_out_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    group_id            NUMBER NOT NULL,
    member_id           NUMBER NOT NULL,
    cycle_end_date      DATE NOT NULL,
    share_amount        NUMBER(12,2) NOT NULL,
    payment_status      VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    paid_date           DATE,
    paid_by_user_id     NUMBER,
    CONSTRAINT pk_share_outs PRIMARY KEY (share_out_id),
    CONSTRAINT fk_share_outs_group FOREIGN KEY (group_id)
        REFERENCES savings_groups (group_id),
    CONSTRAINT fk_share_outs_member FOREIGN KEY (member_id)
        REFERENCES members (member_id),
    CONSTRAINT fk_share_outs_user FOREIGN KEY (paid_by_user_id)
        REFERENCES app_users (user_id),
    CONSTRAINT uq_share_outs_member_cycle UNIQUE (group_id, member_id, cycle_end_date),
    CONSTRAINT chk_share_outs_amount CHECK (share_amount > 0),
    CONSTRAINT chk_share_outs_status CHECK (payment_status IN ('PENDING', 'PAID', 'CANCELLED'))
);

-- Verify the financial tables.
SELECT table_name
FROM user_tables
WHERE table_name IN (
    'CONTRIBUTIONS', 'LOAN_APPLICATIONS', 'LOANS',
    'LOAN_REPAYMENTS', 'PENALTIES', 'SHARE_OUTS'
)
ORDER BY table_name;
