CREATE TABLE public_holidays (
    holiday_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    holiday_date    DATE NOT NULL,
    holiday_name    VARCHAR2(100) NOT NULL,
    description     VARCHAR2(250),
    CONSTRAINT pk_public_holidays PRIMARY KEY (holiday_id),
    CONSTRAINT uq_public_holidays_date UNIQUE (holiday_date)
);

CREATE TABLE audit_log (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    table_name     VARCHAR2(30) NOT NULL,
    action_type    VARCHAR2(10) NOT NULL,
    record_key     VARCHAR2(100),
    old_values     VARCHAR2(4000),
    new_values     VARCHAR2(4000),
    changed_by     VARCHAR2(128) DEFAULT USER NOT NULL,
    changed_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id),
    CONSTRAINT chk_audit_log_action CHECK (action_type IN ('INSERT', 'UPDATE', 'DELETE'))
);

SELECT table_name
FROM user_tables
WHERE table_name IN ('PUBLIC_HOLIDAYS', 'AUDIT_LOG')
ORDER BY table_name;
